Repository meroxa/cli, pull requests merged in 2022-05, with the labels that each got.

#343 fix: version formatting
  cmd/meroxa/main.go
Labels: bug

#358 feat: Only release to homebrew not nightly builds
  .github/workflows/release.yml
Labels: ktlo

#362 chore: Update to go 1.18 and other fixes
  .github/workflows/dispatch_turbine_go_dependency.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .goreleaser.yml
  cmd/meroxa/root/apps/deploy.go
  etc/man/man1/meroxa-api.1
  etc/man/man1/meroxa-apps-deploy.1
  etc/man/man1/meroxa-apps-describe.1
  etc/man/man1/meroxa-apps-init.1
  etc/man/man1/meroxa-apps-list.1
  etc/man/man1/meroxa-apps-remove.1
  etc/man/man1/meroxa-apps-run.1
  etc/man/man1/meroxa-apps.1
  etc/man/man1/meroxa-auth-login.1
  etc/man/man1/meroxa-auth-logout.1
  etc/man/man1/meroxa-auth-whoami.1
  etc/man/man1/meroxa-auth.1
  etc/man/man1/meroxa-billing.1
  etc/man/man1/meroxa-builds-describe.1
  etc/man/man1/meroxa-builds-logs.1
  etc/man/man1/meroxa-builds.1
  etc/man/man1/meroxa-completion.1
  etc/man/man1/meroxa-config-describe.1
  etc/man/man1/meroxa-config.1
  etc/man/man1/meroxa-endpoints-create.1
  etc/man/man1/meroxa-endpoints-describe.1
  etc/man/man1/meroxa-endpoints-list.1
  etc/man/man1/meroxa-endpoints-remove.1
  etc/man/man1/meroxa-endpoints.1
  etc/man/man1/meroxa-environments-create.1
  etc/man/man1/meroxa-environments-describe.1
  etc/man/man1/meroxa-environments-list.1
  etc/man/man1/meroxa-environments-remove.1
  etc/man/man1/meroxa-environments-repair.1
  etc/man/man1/meroxa-environments-update.1
  etc/man/man1/meroxa-environments.1
  etc/man/man1/meroxa-login.1
  etc/man/man1/meroxa-logout.1
  etc/man/man1/meroxa-open-billing.1
  etc/man/man1/meroxa-open.1
  etc/man/man1/meroxa-resources-create.1
  etc/man/man1/meroxa-resources-describe.1
  etc/man/man1/meroxa-resources-list.1
  etc/man/man1/meroxa-resources-remove.1
  etc/man/man1/meroxa-resources-rotate-tunnel-key.1
  etc/man/man1/meroxa-resources-update.1
  etc/man/man1/meroxa-resources-validate.1
  etc/man/man1/meroxa-resources.1
  etc/man/man1/meroxa-transforms-list.1
  etc/man/man1/meroxa-transforms.1
  etc/man/man1/meroxa-version.1
  etc/man/man1/meroxa-whoami.1
  etc/man/man1/meroxa.1
  go.mod
  go.sum
Labels: ktlo

#366 chore: Upgrade to latest turbine-go
  go.mod
  go.sum
  vendor/modules.txt
Labels: ready for review, ktlo

#369 chore: Upgrade to latest turbine-go
  go.mod
  go.sum
  vendor/github.com/meroxa/turbine-go/record.go
  vendor/modules.txt
Labels: ready for review, ktlo
